# Generated by Django 4.2.5 on 2023-09-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_dataentry_created_at_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
